Some installation instructions
xvzcf/VeriFrodo pull request #3
Opened 2021-10-13 18:53 UTC by claucece

2021-10-25 23:48 UTC, xvzcf requested changes

2021-10-25 23:48 UTC, xvzcf commented on install.md
> +1. Install easycrypt:
Should we make this (`Install easycrypt`) a (sub-)section heading and number the bullet points? Same for `2. Install jasmin`

2021-10-25 23:48 UTC, xvzcf commented on install.md
> +		```
Could you also add a step for checking that the installation worked? ([this](https://github.com/xvzcf/VeriFrodo/blob/main/Dockerfile#L39) is how I did it). I've experienced issues in the past with `smt()` calls not working.

2021-10-27 19:01 UTC, claucece commented on install.md
> +1. Install easycrypt:
yes!

2021-10-27 19:03 UTC, claucece commented on install.md
> +		```
added now ;)

2021-10-27 19:47 UTC, xvzcf commented on install.md
> +	cd compiler
I guess we also need a `nix-shell` after this?

2021-10-27 20:11 UTC, xvzcf commented on install.md
> +	git clone git@github.com:jasmin-lang/jasmin.git
We also need the `glob_array3` branch.

2022-01-28 18:28 UTC, merged